include:
  - board: nice_nano@2.0.0//zmk
    shield: keyball39_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: keyball39_central_dongle_oled

  - board: nice_nano@2.0.0//zmk
    shield: keyball39_central_dongle_noscreen
    snippet: studio-rpc-usb-uart
    artifact-name: keyball39_central_dongle_noscreen

  - board: nice_nano@2.0.0//zmk
    shield: keyball39_left nice_view_adapter keyball39_esb_nice_view
    artifact-name: keyball39_left-nice_nano_v2

  - board: nice_nano@2.0.0//zmk
    shield: keyball39_right nice_view_adapter keyball39_esb_nice_view
    artifact-name: keyball39_right-nice_nano_v2

  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
    artifact-name: settings_reset-nice_nano_v2
