CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

CONFIG_ZMK_BLE=n
CONFIG_ZMK_USB=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n
CONFIG_ZMK_SPLIT_ESB=y
CONFIG_ZMK_SPLIT_ESB_PERIPHERAL_ID=2
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_ACK=y
CONFIG_ZMK_SPLIT_ESB_PROTO_MSGQ_ITEMS=64
CONFIG_ZMK_SPLIT_ESB_EVENT_BUFFER_ITEMS=64
CONFIG_ZMK_SPLIT_ESB_CMD_BUFFER_ITEMS=16
CONFIG_ZMK_SPLIT_ESB_MSGQ_FULL_TIMEOUT_MS=1000
CONFIG_ZMK_SPLIT_ESB_RETRY_KEY_POSITION=9

CONFIG_MPSL_TIMESLOT_SESSION_COUNT=1
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_ESB_MAX_PAYLOAD_LENGTH=48
CONFIG_ESB_TX_FIFO_SIZE=1
CONFIG_MPSL_ASSERT_HANDLER=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_IDLE_STACK_SIZE=512
CONFIG_HW_STACK_PROTECTION=y
CONFIG_STACK_SENTINEL=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_MODE_OVERFLOW=y
CONFIG_LOG_PROCESS_THREAD_PRIORITY=10
CONFIG_USB_WORKQUEUE_STACK_SIZE=4096
CONFIG_USB_CDC_ACM_RINGBUF_SIZE=1024
CONFIG_INPUT_THREAD_STACK_SIZE=8192
CONFIG_INPUT_QUEUE_MAX_MSGS=512

CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_PMW3610=y
CONFIG_PM_DEVICE=y
CONFIG_PMW3610_PM=y
CONFIG_PMW3610_CPI=1200
CONFIG_PMW3610_CPI_DIVIDOR=4
CONFIG_PMW3610_ORIENTATION_180=y
CONFIG_PMW3610_SNIPE_CPI=400
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=4
CONFIG_PMW3610_SCROLL_TICK=32
CONFIG_PMW3610_INVERT_SCROLL_X=y
CONFIG_PMW3610_INVERT_SCROLL_Y=n
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20
#CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=9600
#CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=
#CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=
#CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=
#CONFIG_PMW3610_REST3_DOWNSHIFT_TIME_MS=
#CONFIG_PMW3610_FORCE_AWAKE=n
#CONFIG_PMW3610_POLLING_RATE_125_SW=y
CONFIG_PMW3610_POLLING_RATE_250=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=700
CONFIG_PMW3610_MOVEMENT_THRESHOLD=0
